import { useTranslation } from "react-i18next";
import { Droplet, Leaf, ShieldAlert, Sparkles, Sprout, TrendingDown } from "lucide-react";

export default function ClimateSmart() {
  const { t } = useTranslation();

  const metrics = [
    {
      label: t("climateSmart.stat1Title", { defaultValue: "Water Efficiency" }),
      val: "38%",
      desc: t("climateSmart.stat1Desc", { defaultValue: "Reduction in consumption" }),
      icon: Droplet,
      accent: "text-sky-700 dark:text-sky-400",
      bg: "bg-sky-50 dark:bg-sky-950/40",
    },
    {
      label: t("climateSmart.stat2Title", { defaultValue: "Carbon Offset" }),
      val: "1.8t",
      desc: t("climateSmart.stat2Desc", { defaultValue: "Annual metric tons/farm" }),
      icon: Leaf,
      accent: "text-emerald-700 dark:text-emerald-400",
      bg: "bg-emerald-50 dark:bg-emerald-950/40",
    },
    {
      label: t("climateSmart.stat3Title", { defaultValue: "Soil Health Index" }),
      val: "94%",
      desc: t("climateSmart.stat3Desc", { defaultValue: "Nutrient balance retention" }),
      icon: Sprout,
      accent: "text-teal-700 dark:text-teal-400",
      bg: "bg-teal-50 dark:bg-teal-950/40",
    },
    {
      label: t("climateSmart.stat4Title", { defaultValue: "Chemical Input Cut" }),
      val: "22%",
      desc: t("climateSmart.stat4Desc", { defaultValue: "Targeted fertilizer dosing" }),
      icon: TrendingDown,
      accent: "text-amber-700 dark:text-amber-400",
      bg: "bg-amber-50 dark:bg-amber-950/40",
    },
  ];

  return (
    <section className="py-20 sm:py-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-stone-900 dark:text-stone-100 transition-colors">
      <div className="grid lg:grid-cols-12 gap-12 items-center">

        {/* Left Column: Vision & Narrative */}
        <div className="lg:col-span-5 space-y-5 text-center lg:text-left">
          <span className="inline-flex items-center gap-1.5 text-xs sm:text-sm font-bold uppercase tracking-widest text-emerald-800 dark:text-emerald-400 bg-emerald-100/70 dark:bg-emerald-950/50 px-3.5 py-1.5 rounded-full">
            <Leaf size={14} />
            {t("climateSmart.badgeEnv", { defaultValue: "Environmental Impact" })}
          </span>

          <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold text-stone-900 dark:text-white tracking-tight leading-tight">
            {t("climateSmart.title", { defaultValue: "Climate-Smart by Design" })}
          </h2>

          <p className="text-base sm:text-lg text-stone-600 dark:text-stone-300 leading-relaxed font-normal">
            {t("climateSmart.desc", {
              defaultValue:
                "Every recommendation generated by our AI is optimized for high yield while minimizing resource depletion and preserving soil microbial biodiversity.",
            })}
          </p>

          <div className="pt-2 text-xs text-stone-500 dark:text-stone-400 flex items-center justify-center lg:justify-start gap-2">
            <span className="w-2 h-2 rounded-full bg-emerald-500" />
            <span>Targeting UN Sustainable Development Goals 2, 12, & 13</span>
          </div>
        </div>

        {/* Right Column: 4 Environmental Target Cards */}
        <div className="lg:col-span-7">
          <div className="flex items-center justify-between mb-4 px-1">
            <span className="text-xs font-bold bg-emerald-100/80 dark:bg-emerald-950/60 text-emerald-800 dark:text-emerald-300 px-3 py-1 rounded-full border border-emerald-200/60 dark:border-emerald-800">
              {t("climateSmart.badgeTargets", { defaultValue: "Projected Targets" })}
            </span>
            <span className="text-xs text-stone-400">
              {t("climateSmart.note", { defaultValue: "Pilot model projections" })}
            </span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {metrics.map((item, i) => {
              const Icon = item.icon;
              return (
                <div
                  key={i}
                  className="bg-white dark:bg-stone-900 p-6 rounded-3xl border border-stone-200/80 dark:border-stone-800 shadow-card hover:shadow-card-hover transition-all"
                >
                  <div className="flex items-center justify-between mb-3">
                    <div className={`w-10 h-10 rounded-2xl ${item.bg} flex items-center justify-center ${item.accent}`}>
                      <Icon size={20} />
                    </div>
                    <div className="text-3xl font-black text-stone-900 dark:text-white tracking-tight">
                      {item.val}
                    </div>
                  </div>

                  <div className="font-bold text-sm sm:text-base text-stone-900 dark:text-white">
                    {item.label}
                  </div>
                  <div className="text-xs text-stone-500 dark:text-stone-400 mt-1">
                    {item.desc}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

      </div>
    </section>
  );
}